import React, { type ReactNode } from "react";

import { Footer } from "@/components/layout/footer";
import { LenisWrapper } from "@/lib/lenis/lenis";

import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <html lang="pl">
      <LenisWrapper>
        <body>{children}
          <Footer />
        </body>

      </LenisWrapper>
    </html>
  );
};

export default RootLayout;
